name: evently
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  # changed from 3.9.2 to a standard range
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  hydrated_bloc: ^9.1.2 # Version 10+ often has breaking changes, 9.x is safer for now
  path_provider: ^2.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5 # Highly recommended when using Bloc
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # ⚠️ IMPORTANT:
  # Move your 'assets' folder OUT of 'lib'.
  # It should be at the top level of your project:
  # evently/assets/images/logo.svg
  assets:
    - assets/images/logo.svg
